runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

handlers:

- url: /ihex-web.js
  static_files: static/ihex-web.js
  upload: static/ihex-web.js

- url: /node_modules
  static_dir: static/node_modules
  secure: always

- url: /samples
  static_dir: static/samples
  secure: always

- url: /hterm_all.js
  static_files: static/hterm_all.js
  upload: static/hterm_all.js

- url: .*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?bower\.json
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^.*.md|markdown
